title: elementary Developer Weekend
description: June 26–27, 2021
author: elementary, Inc.
color: "#452981"
image: https://edw.elementary.io/card.png
twitter: "@elementary"
donate: https://elementary.io/get-involved#funding

# Settings
markdown: kramdown
